### ISSUE TITLE
Setting값 구조 잡기

### ISSUE THREAD

**Issue by lbr0452000** [ProjectInTheClass/CAUDormitory#9]
다음과 같은 정보를 담고 있는 객체를 생성해야 함
다음의 정보는 어플의 기본 정보를 담고 있고, UserDefault값과 연동되어야 함

사용자 정보
ㄴ학번 : Int
ㄴ성별 : String
호실 정보
ㄴ건물 : DormitoryBuilding
ㄴ호실 : Int
푸시알림(On/Off) : Bool
ㄴ정기점검 : Bool
ㄴ방역소독 : Bool
ㄴ정기소방훈련 : Bool
ㄴ입관신청 : Bool
ㄴ퇴관신청 : Bool

**Comment by lbr0452000** [comment]
e153b6e1890d5eb436f82576eff8bd9ecd736247 커밋에서 대략적인 구조를 확정지었습니다.

**Comment by lbr0452000** [comment]
사용자 정보
ㄴ학번 : Int
ㄴ성별 : String
호실 정보
ㄴ건물 : DormitoryBuilding
ㄴ호실 : Int

위의 네 개의 Setting값은 각각 rawValue를 지정한 다음, 모두 UserDefaults.standard.integer형식으로 불러올 수 있게끔 만들었습니다. a22705309e04c1f01f77f32fea734922e07a0791 커밋에서 거의 이런 형식으로 구조화를 마쳤습니다.

**Comment by Jinsu5606** [comment]
309관과 308관 오타있습니다!

**Comment by lbr0452000** [comment]
@jinsu5656 46caaa82590699bfafdab26f3db7080bb06a963e 에서 해결되었습니다

**Comment by lbr0452000** [comment]
5b2aef9da20d340f20073a19a5d4482f5240a877 에서 setting값에 관한 구조화가 완료되었습니다.
